### ISSUE TITLE
Setup dapr and debug run environment

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/template-microservice#7]
## Parent issue
https://github.com/IT-REX-Platform/wiki/issues/8

## Description
Set up dapr for the real project in a sophisticated way in a separate docker container.

## Acceptance Criteria
- [x] dapr is ready to use
- [x] Basic setup to run dapr instances with microservices in a nice way (Docker containers)
- [ ] IntelliJ run configurations
- [x] documentation is updated if necessary

**Comment by PaulBredl** [comment]
@LG1401 this is done IMO. 

IntelliJ run configuration are not necessary (IntelliJ automatically creates them when you run the app or a script). Also they would not be pushed to the repository.
